version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: services_platform_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: services_platform

      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
